--------------------------------------------------------------------------
--									--
--									--
--				ctrl.lua by By FlashStep		--
--									--
--									--
--------------------------------------------------------------------------
print( "Loading Hellchapter Ctrl.lua" )

function config(map)
    MapCanSavePos(map, 0)		-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
    MapCanPK(map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCopyNum(map, 1)			-- 1 Copy of the map will be generated by GameServer
    MapCopyStartType(map, 1) 		-- 设置地图立即开始
    SingleMapCopyPlyNum(map, 300) 	-- 300 Players are allowed to enter the map
    MapCanTeam(map , 1)			-- 1 = Allow players to create party // 0 = Do not allow players to create party
    MapType ( map , 4 )			-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
end


function get_map_entry_pos_Hellchapter()   --设置入口的位置的坐标（坐标（米））

end

function init_entry(map)
   
end

function after_enter_Hellchapter( role , map_copy )

local cha_name=GetChaDefaultName(role)

	SystemNotice ( role, "\199\228\240\224\226\241\242\226\243\233 "..cha_name.." \196\238\225\240\238 \239\238\230\224\235\238\226\224\242\252 \226 \192\228! " ) 

end

function before_leave_Hellchapter( role )

end

function map_copy_first_run_Hellchapter( map_copy )

end

function map_copy_run_Hellchapter( map_copy )

end

--每5秒执行一次的
function map_run_Hellchapter( map )

end

--地图关闭时执行
function map_copy_close_Hellchapter( map_copy )

end