-- volcanoisle Edit By SuperHuman--

function config(map)
    MapCanSavePos(map, 0)		-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
    MapCanPK(map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCopyNum(map, 1)			-- 1 Copy of the map will be generated by GameServer
    SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
    MapCanTeam(map , 1)			-- 1 = Allow players to create party // 0 = Do not allow players to create party
    MapType ( map , 4 )			-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        

end


function get_map_entry_pos_volcanoisle()   --设置入口的位置的坐标（坐标（米））

	local POS_X=65
	local POS_Y=30
	return POS_X , POS_Y

end

function init_entry(map)
    SetMapEntryMapName(map, "fishing") --This Is where the portal map located
end

function map_run_volcanoisle( map )

end

function map_copy_run_volcanoisle(map_copy)
end