 --------------------------------------------------------------------------
--									--
--									--
--				ctrl.lua				--
--									--
--									--
--------------------------------------------------------------------------
print( "Loading bosshotel Ctrl.lua" )


--此文件中，凡是可能被多次执行的函数，函数名都要加上地图名前缀

function config(map)
    MapCanSavePos(map, 0)		-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
    MapCanPK(map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCanTeam( map, 1 )		-- 1 = Allow players to create party // 0 = Do not allow players to create party
    MapType( map , 1 )			-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCopyNum(map, 1)			-- 1 Copy of the map will be generated by GameServer
    SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
    MapCanStall(map , 0)		-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end


function get_map_entry_pos_bosshotel()   --设置入口的位置的坐标（坐标（米））

	local POS_X=899
	local POS_Y=3588
	return POS_X , POS_Y

end

function init_entry(map)

    SetMapEntryMapName(map, "magicsea") --设置入口的位置（地图名）
    SetMapEntryTime(map, "2008/10/18/10/0", "0/1/0", "0/1/0", "0/1/0")	-- The first set of numbers is the starting point (Year/Month/Day/Hour/Minute), next is opening interval (Day/Hour/Minute), portal open duration (Day/Hour/Minute), and last is the map duration (Day/Hour/Minute)

end

function after_enter_bosshotel( role , map_copy )
end

function before_leave_bosshotel( role )
end

--function map_copy_first_run_bosshotel( map_copy )
--	lua_SetCopySpecialInter(map_copy , 10000)
--	Notice("10")
--
--end

--function map_copy_run_bosshotel( map_copy )
----Notice("3")
--local new1 = CreateChaEx(791, 120, 120, 145, 50)
--	SetChaLifeTime(new1, 900000)
--		
--end

--每5秒执行一次的
function map_run_bosshotel( map )
	
end

--地图关闭时执行
function map_copy_before_close_bosshotel( map_copy )
	How_Many_Active = GetMapActivePlayer(map_copy)
	if How_Many_Active > 0 then
		DealAllActivePlayerInMap(map_copy,"GiveSpecItem")
	end
	How_Many_Active = 0
	Money_all = 1000000
	Every_5_minute = 0
end

--地图关闭时执行
function map_copy_close_bosshotel( map_copy )
	ClearAllSubMapCha(map_copy)
end
--
--地图开关判断——————————————————————————————————————————

function can_open_entry_bosshotel( map ) 
--	local time = GetTickCount ( ) 
	local Now_Time = GetNowTime()
	if Now_Time ==14 or Now_Time == 20 then
		return 1
	else
		return 1
	end

end 

