--------------------------
--- Piratia Online 		--
--- Graf		   		--
--- Moroz		   		--
--- 2021		   		--
--- Discord - Graf#4664 --
--------------------------
-- --------------------------
-- Display loading message on startup
-- --------------------------
local MAP_NAME = "Slayer Rumble"
local MAP_AUTHOR = "Sultan"
print(">> Loading map "..MAP_NAME.." from "..MAP_AUTHOR)

-- ---------------------------
-- Load Conf.lua
-- ---------------------------
dofile(GetResPath("SlayerRumble/conf.lua"))

-- ---------------------------
-- Loading Ctrl.lua
-- ---------------------------
print("	>> Loading Ctrl.lua")
function config(map)
    MapCanSavePos(map, 0)		-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
    MapCanPK(map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCanTeam( map, 0 )		-- 1 = Allow players to create party // 0 = Do not allow players to create party
    MapType( map , 3 )			-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCopyNum(map, 1)			-- 1 Copy of the map will be generated by GameServer
    SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
    MapCanStall(map , 0)		-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end


function get_map_entry_pos_SlayerRumble()
	return SlayerRumble.Portal.X , SlayerRumble.Portal.Y
end

function init_entry(map)
    SetMapEntryMapName(map, SlayerRumble.Portal.Map)
    SetMapEntryTime(map, "2013/07/12/0/0", SlayerRumble.Time.Open, SlayerRumble.Time.Close, SlayerRumble.Time.Shutdown)
end

function after_enter_SlayerRumble( role , map_copy )
	local CharacterName = GetChaDefaultName(role)
	if(SlayerRumble.Players[CharacterName] == nil)then
		SlayerRumble.Players[CharacterName] = { Lives = 3, Inside = true, Role = role }
	else
		SlayerRumble.Players[CharacterName].Inside = true
	end
	SlayerRumble.PlayerCounts = SlayerRumble.PlayerCounts + 1
	Notice(CharacterName.." \231\224\248\184\235 \237\224 \206\241\242\240\238\226 \193\238\227\224\242\241\242\226\224! ")
end

function before_leave_SlayerRumble( role )
	local CharacterName = GetChaDefaultName(role)
	if(SlayerRumble.Players[CharacterName] ~= nil)then
		if(Hp(role) > 0)then
			SlayerRumble.Players[CharacterName].Lives = SlayerRumble.Players[CharacterName].Lives - 1
		end
		SlayerRumble.Players[CharacterName].Inside = false
	end	
	SlayerRumble.PlayerCounts = SlayerRumble.PlayerCounts - 1
end

function SlayerRumblePK(Killer, Dead)
	local KillerName = GetChaDefaultName(Killer)
	local DeadName = GetChaDefaultName(Dead)
	Notice("[\206\241\242\240\238\226 \193\238\227\224\242\241\242\226\224] \232\227\240\238\234 ["..DeadName.."] \238\242\245\226\224\242\232\235 \238\242 ["..KillerName.."] ")
	
	SlayerRumble.Players[KillerName].Lives = SlayerRumble.Players[KillerName].Lives + 1
	SystemNotice(Killer, "\202\238\235\232\247\229\241\242\226\238 \226\245\238\228\238\226 = "..SlayerRumble.Players[KillerName].Lives)
	
	SlayerRumble.Players[DeadName].Inside = false
	SlayerRumble.Players[DeadName].Lives = SlayerRumble.Players[DeadName].Lives - 1
	SystemNotice(Dead, "\202\238\235\232\247\229\241\242\226\238 \226\245\238\228\238\226 = "..SlayerRumble.Players[DeadName].Lives)
end

function map_copy_run_special_SlayerRumble( map_copy ) 
	local HowManyNoDead = GetMapActivePlayer(map_copy)
	if HowManyNoDead > 4 and HowManyNoDead <= 20 then
	Notice("\205\224 \206\241\242\240\238\226\229 \193\238\227\224\242\241\242\226\224 \229\249\184 \230\232\226\251 "..HowManyNoDead.." \232\227\240\238\234\238\226 " )
	elseif HowManyNoDead > 1 and HowManyNoDead <= 4 then
	Notice("\205\224 \206\241\242\240\238\226\229 \193\238\227\224\242\241\242\226\224 \229\249\184 \230\232\226\251 "..HowManyNoDead.." \232\227\240\238\234\224 " )
	elseif HowManyNoDead > 21 and HowManyNoDead <= 24 then
	Notice("\205\224 \206\241\242\240\238\226\229 \193\238\227\224\242\241\242\226\224 \229\249\184 \230\232\226\251 "..HowManyNoDead.." \232\227\240\238\234\224 " )
	elseif HowManyNoDead > 24 and HowManyNoDead <= 70 then
	Notice("\205\224 \206\241\242\240\238\226\229 \193\238\227\224\242\241\242\226\224 \229\249\184 \230\232\226\251 "..HowManyNoDead.." \232\227\240\238\234\238\226 " )
	elseif HowManyNoDead == 1 then
	Notice("\205\224 \206\241\242\240\238\226\229 \193\238\227\224\242\241\242\226\224 \229\249\184 \230\232\226 "..HowManyNoDead.." \232\227\240\238\234 " )
	else
		Notice("\205\224 \206\241\242\240\238\226\229 \193\238\227\224\242\241\242\226\224 \237\229\242 \237\232 \238\228\237\238\227\238 \232\227\240\238\234\224 ")
	end
	Every_5_minute3 = Every_5_minute3 + 1
	
	if Every_5_minute3 == 1 then
		local Monster2 = CreateChaEx(1670, 6500, 6100, 145, 60,map_copy)
		local Monster3 = CreateChaEx(1670, 6900, 5800, 145, 60,map_copy)
		local Monster4 = CreateChaEx(1670, 6500, 5300, 145, 60,map_copy)
		local Monster5 = CreateChaEx(1670, 6200, 5700, 145, 60,map_copy)
		local Monster6 = CreateChaEx(1670, 5800, 6500, 145, 60,map_copy)
		local Monster7 = CreateChaEx(1670, 5400, 5500, 145, 60,map_copy)
		local Monster8 = CreateChaEx(1670, 5800, 4700, 145, 60,map_copy)
		local Monster9 = CreateChaEx(1670, 6800, 4600, 145, 60,map_copy)
		local Monster10 = CreateChaEx(1670, 8000, 5300, 145, 60,map_copy)
		local Monster11 = CreateChaEx(1670, 7500, 7300, 145, 60,map_copy)
		local Monster12 = CreateChaEx(1670, 5300, 7200, 145, 60,map_copy)
		local Monster13 = CreateChaEx(1670, 6500, 4000, 145, 60,map_copy)
		local Monster14 = CreateChaEx(1670, 6600, 7800, 145, 60,map_copy)
		local Monster15 = CreateChaEx(1670, 4200, 4800, 145, 60,map_copy)
		local Monster16 = CreateChaEx(1670, 4200, 5700, 145, 60,map_copy)
		local Monster17 = CreateChaEx(1670, 4300, 6600, 145, 60,map_copy)
		local Monster18 = CreateChaEx(1670, 3900, 7200, 145, 60,map_copy)
		local Monster19 = CreateChaEx(1674, 5100, 11800, 145, 60,map_copy)
		local Monster20 = CreateChaEx(1674, 5000, 4300, 145, 60,map_copy)
		local Monster21 = CreateChaEx(1674, 10900, 5100, 145, 60,map_copy)
		local Monster22 = CreateChaEx(1674, 8500, 9400, 145, 60,map_copy)
		local Monster23 = CreateChaEx(1674, 10800, 11900, 145, 60,map_copy)		
		SetChaLifeTime(Monster2,297050)
		SetChaLifeTime(Monster3,297100)
		SetChaLifeTime(Monster4,297150)
		SetChaLifeTime(Monster5,297200)
		SetChaLifeTime(Monster6,297250)
		SetChaLifeTime(Monster7,297300)
		SetChaLifeTime(Monster8,297350)
		SetChaLifeTime(Monster9,297400)
		SetChaLifeTime(Monster10,297450)
		SetChaLifeTime(Monster11,297500)
		SetChaLifeTime(Monster12,297550)
		SetChaLifeTime(Monster13,297600)
		SetChaLifeTime(Monster14,297650)
		SetChaLifeTime(Monster15,297700)
		SetChaLifeTime(Monster16,297750)
		SetChaLifeTime(Monster17,297800)
		SetChaLifeTime(Monster18,297850)
		SetChaLifeTime(Monster19,297900)
		SetChaLifeTime(Monster20,297950)
		SetChaLifeTime(Monster21,297000)
		SetChaLifeTime(Monster22,296050)
		SetChaLifeTime(Monster23,296150)
end
		
		if Every_5_minute3 == 3 then -- 初级宝箱
		local Monster24 = CreateChaEx(1671, 6500, 5200, 145, 60,map_copy)
		local Monster25 = CreateChaEx(1671, 6100, 5700, 145, 60,map_copy)
		local Monster26 = CreateChaEx(1671, 6600, 6200, 145, 60,map_copy)
		local Monster27 = CreateChaEx(1671, 5600, 6700, 145, 60,map_copy)
		local Monster28 = CreateChaEx(1671, 5000, 6600, 145, 60,map_copy)
		local Monster29 = CreateChaEx(1671, 5100, 5800, 145, 60,map_copy)
		local Monster30 = CreateChaEx(1671, 5300, 5100, 145, 60,map_copy)
		local Monster31 = CreateChaEx(1671, 6100, 4700, 145, 60,map_copy)
		local Monster32 = CreateChaEx(1671, 5100, 4300, 145, 60,map_copy)
		local Monster33 = CreateChaEx(1671, 4700, 4700, 145, 60,map_copy)
		local Monster34 = CreateChaEx(1671, 6400, 7000, 145, 60,map_copy)
		local Monster35 = CreateChaEx(1671, 7000, 7500, 145, 60,map_copy)
		local Monster36 = CreateChaEx(1671, 7900, 6900, 145, 60,map_copy)
		local Monster37 = CreateChaEx(1671, 8000, 5900, 145, 60,map_copy)
		local Monster38 = CreateChaEx(1674, 5000, 4300, 145, 60,map_copy)
		local Monster39 = CreateChaEx(1674, 10900, 5100, 145, 60,map_copy)
		local Monster40 = CreateChaEx(1674, 8500, 9400, 145, 60,map_copy)
		local Monster41 = CreateChaEx(1674, 10800, 11900, 145, 60,map_copy)
		local Monster42 = CreateChaEx(1674, 8500, 9400, 145, 60,map_copy)
		local Monster43 = CreateChaEx(1678, 5100, 11300, 145, 60,map_copy)
		SetChaLifeTime(Monster24,297050)
		SetChaLifeTime(Monster25,297100)
		SetChaLifeTime(Monster26,297150)
		SetChaLifeTime(Monster27,297200)
		SetChaLifeTime(Monster28,297250)
		SetChaLifeTime(Monster29,297300)
		SetChaLifeTime(Monster30,297350)
		SetChaLifeTime(Monster31,297400)
		SetChaLifeTime(Monster32,297450)
		SetChaLifeTime(Monster33,297500)
		SetChaLifeTime(Monster34,297550)
		SetChaLifeTime(Monster35,297600)
		SetChaLifeTime(Monster36,297650)
		SetChaLifeTime(Monster37,297700)
		SetChaLifeTime(Monster38,297750)
		SetChaLifeTime(Monster39,297800)
		SetChaLifeTime(Monster40,297850)
		SetChaLifeTime(Monster41,297900)
		SetChaLifeTime(Monster42,297950)
		SetChaLifeTime(Monster43,296150)
		
end
		if Every_5_minute3 == 4 then -- 初级宝箱
		local Monster44 = CreateChaEx(1672, 6500, 5800, 145, 60,map_copy)
		local Monster45 = CreateChaEx(1672, 6200, 6100, 145, 60,map_copy)
		local Monster46 = CreateChaEx(1672, 6800, 6100, 145, 60,map_copy)
		local Monster47 = CreateChaEx(1672, 6500, 5300, 145, 60,map_copy)
		local Monster48 = CreateChaEx(1672, 5000, 6600, 145, 60,map_copy)
		local Monster49 = CreateChaEx(1672, 5100, 5800, 145, 60,map_copy)
		local Monster50 = CreateChaEx(1672, 5300, 5100, 145, 60,map_copy)
		local Monster51 = CreateChaEx(1672, 6100, 4700, 145, 60,map_copy)
		local Monster52 = CreateChaEx(1672, 5100, 4300, 145, 60,map_copy)
		local Monster53 = CreateChaEx(1672, 4700, 4700, 145, 60,map_copy)
		local Monster54 = CreateChaEx(1672, 6400, 7000, 145, 60,map_copy)
		local Monster55 = CreateChaEx(1672, 7000, 7500, 145, 60,map_copy)
		local Monster56 = CreateChaEx(1672, 7900, 6900, 145, 60,map_copy)
		local Monster57 = CreateChaEx(1672, 8000, 5900, 145, 60,map_copy)
		local Monster58 = CreateChaEx(1674, 5000, 4300, 145, 60,map_copy)
		local Monster59 = CreateChaEx(1674, 10900, 5100, 145, 60,map_copy)
		local Monster60 = CreateChaEx(1674, 8500, 9400, 145, 60,map_copy)
		local Monster61 = CreateChaEx(1674, 10800, 11900, 145, 60,map_copy)
		local Monster62 = CreateChaEx(1674, 8500, 9400, 145, 60,map_copy)
		local Monster63 = CreateChaEx(1679, 5100, 11300, 145, 60,map_copy)
		SetChaLifeTime(Monster44,297050)
		SetChaLifeTime(Monster45,297100)
		SetChaLifeTime(Monster46,297150)
		SetChaLifeTime(Monster47,297200)
		SetChaLifeTime(Monster48,297250)
		SetChaLifeTime(Monster49,297300)
		SetChaLifeTime(Monster50,297350)
		SetChaLifeTime(Monster51,297400)
		SetChaLifeTime(Monster52,297450)
		SetChaLifeTime(Monster53,297500)
		SetChaLifeTime(Monster54,297550)
		SetChaLifeTime(Monster55,297600)
		SetChaLifeTime(Monster56,297650)
		SetChaLifeTime(Monster57,297700)
		SetChaLifeTime(Monster58,297750)
		SetChaLifeTime(Monster59,297800)
		SetChaLifeTime(Monster60,297850)
		SetChaLifeTime(Monster61,297900)
		SetChaLifeTime(Monster62,297950)
		SetChaLifeTime(Monster63,296150)
		end

		if Every_5_minute3 == 5 then -- 初级宝箱
		local Monster64 = CreateChaEx(1673, 6500, 5800, 145, 60,map_copy)
		local Monster65 = CreateChaEx(1673, 6500, 5300, 145, 60,map_copy)
		local Monster66 = CreateChaEx(1673, 6500, 6100, 145, 60,map_copy)
		local Monster67 = CreateChaEx(1673, 5600, 6700, 145, 60,map_copy)
		local Monster68 = CreateChaEx(1673, 5000, 6600, 145, 60,map_copy)
		local Monster69 = CreateChaEx(1673, 5100, 5800, 145, 60,map_copy)
		local Monster70 = CreateChaEx(1673, 5300, 5100, 145, 60,map_copy)
		local Monster71 = CreateChaEx(1673, 6100, 4700, 145, 60,map_copy)
		local Monster72 = CreateChaEx(1673, 5100, 4300, 145, 60,map_copy)
		local Monster73 = CreateChaEx(1673, 4700, 4700, 145, 60,map_copy)
		local Monster74 = CreateChaEx(1673, 6400, 7000, 145, 60,map_copy)
		local Monster75 = CreateChaEx(1673, 7000, 7500, 145, 60,map_copy)
		local Monster76 = CreateChaEx(1673, 7900, 6900, 145, 60,map_copy)
		local Monster77 = CreateChaEx(1673, 8000, 5900, 145, 60,map_copy)
		local Monster78 = CreateChaEx(1674, 5000, 4300, 145, 60,map_copy)
		local Monster79 = CreateChaEx(1674, 10900, 5100, 145, 60,map_copy)
		local Monster80 = CreateChaEx(1674, 8500, 9400, 145, 60,map_copy)
		local Monster81 = CreateChaEx(1674, 10800, 11900, 145, 60,map_copy)
		local Monster82 = CreateChaEx(1674, 8500, 9400, 145, 60,map_copy)
		local Monster83 = CreateChaEx(1680, 5100, 11300, 145, 60,map_copy)
		SetChaLifeTime(Monster64,297050)
		SetChaLifeTime(Monster65,297100)
		SetChaLifeTime(Monster66,297150)
		SetChaLifeTime(Monster67,297200)
		SetChaLifeTime(Monster68,297250)
		SetChaLifeTime(Monster69,297300)
		SetChaLifeTime(Monster70,297350)
		SetChaLifeTime(Monster71,297400)
		SetChaLifeTime(Monster72,297450)
		SetChaLifeTime(Monster73,297500)
		SetChaLifeTime(Monster74,297550)
		SetChaLifeTime(Monster75,297600)
		SetChaLifeTime(Monster76,297650)
		SetChaLifeTime(Monster77,297700)
		SetChaLifeTime(Monster78,297750)
		SetChaLifeTime(Monster79,297800)
		SetChaLifeTime(Monster80,297850)
		SetChaLifeTime(Monster81,297900)
		SetChaLifeTime(Monster82,297950)
		SetChaLifeTime(Monster83,296150)
		end
		end
		

function TakePlayersOut(role)

end

function map_run_SlayerRumble( map )
end

function map_copy_before_close_SlayerRumble( map_copy )
Every_5_minute3 = 0
SlayerRumble:Init()
SlayerRumble.Opened = false
end

function map_copy_close_SlayerRumble( map_copy )
ClearAllSubMapCha(map_copy)
end

function can_open_entry_SlayerRumble( map )
	return 1
end
