--------------------------------------------------------------------------
--									--
--									--
--				ctrl.lua				--
--									--
--									--
--------------------------------------------------------------------------
print( "Loading CrystalShore Ctrl.lua" )


function config(map)
    MapCanSavePos(map, 1)		-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
    MapCanPK(map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCanTeam(map , 1)			-- 1 = Allow players to create party // 0 = Do not allow players to create party
    SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
    MapCopyNum(map, 1)			-- 1 Copy of the map will be generated by GameServer
    MapType ( map , 3 )			-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
end


function get_map_entry_pos_CrystalShore()

end


function init_entry(map)

end


function after_enter_CrystalShore( role , map_copy )
end


function before_leave_CrystalShore( role )
end


function map_copy_first_run_CrystalShore( map_copy )

end


function map_copy_run_CrystalShore( map_copy )
end


function map_run_CrystalShore( map )
end


function map_copy_close_CrystalShore ( map_copy )
end
		

function can_open_entry_CrystalShore( map ) 
end 

function map_copy_run_special_CrystalShore( map_copy )

end