--------------------------------------------------------------------------
--									--
--									--
--				ctrl.lua				--
--									--
--									--
--------------------------------------------------------------------------
print( "Loading avc1 Ctrl.lua" )


--此文件中，凡是可能被多次执行的函数，函数名都要加上地图名前缀

function config(map)
    MapCanSavePos(map, 0)		-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
    MapCanPK(map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCanTeam( map, 1 )		-- 1 = Allow players to create party // 0 = Do not allow players to create party
    MapType( map , 3 )			-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCopyNum(map, 1)			-- 1 Copy of the map will be generated by GameServer
    SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
    MapCanStall(map , 0)		-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end


function get_map_entry_pos_avc1()   --设置入口的位置的坐标（坐标（米））

	local POS_X=813
	local POS_Y=3586
	return POS_X , POS_Y

end

function init_entry(map)

    SetMapEntryMapName(map, "magicsea") --设置入口的位置（地图名）
    SetMapEntryTime(map, "2008/10/18/10/0", "0/1/0", "0/0/30", "0/0/45")	-- The first set of numbers is the starting point (Year/Month/Day/Hour/Minute), next is opening interval (Day/Hour/Minute), portal open duration (Day/Hour/Minute), and last is the map duration (Day/Hour/Minute)

end

function after_enter_avc1( role , map_copy )
end

function before_leave_avc1( role )
end

--function map_copy_first_run_avc1( map_copy )
--	lua_SetCopySpecialInter(map_copy , 10000)
--	Notice("10")
--
--end

--function map_copy_run_avc1( map_copy )
----Notice("3")
--local new1 = CreateChaEx(791, 120, 120, 145, 50)
--	SetChaLifeTime(new1, 900000)
--		
--end

--每5分钟秒执行1次
function map_copy_run_special_avc1( map_copy ) 

end
--每5秒执行一次的
function map_run_avc1( map )
	
end

--地图关闭时执行
function map_copy_before_close_avc1( map_copy )
	
end

--地图关闭时执行
function map_copy_close_avc1( map_copy )
	ClearAllSubMapCha(map_copy)
end
--
--地图开关判断——————————————————————————————————————————

function can_open_entry_avc1( map ) 


end 


function GiveSpecItem( role )
	
end 